name = "Craftpunk Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68f33ca9b0f39f9a443f1dc3dada4aeb47d2eca50375171aa4b11cee7f31a5ad"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
